config/routes.rb
Rails.application.routes.draw do
  resources :lives

  resources :stories

  resources :cards

  root 'cards#index'

  get 'news' => 'cards#news'
  get 'cover-app' => 'cards#cover'

  
end

app/models/card.rb
class Card < ActiveRecord::Base
end

app/models/live.rb
class Live < ActiveRecord::Base
end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

  end

  def news
    @@data = File.read(Rails.root + "public/static/news.json")
    render :json => @@data
  end

  def cover
    @@data = File.read(Rails.root + "public/static/cover-app.json")
    render :json => @@data
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :subtitle, :photo, :publish_date, :card_type, :tag, :card_url, :source, :sponsor, :source_name)
    end
end

app/controllers/lives_controller.rb
class LivesController < ApplicationController
  before_action :set_life, only: [:show, :edit, :update, :destroy]

  # GET /lives
  # GET /lives.json
  def index
    @lives = Live.all
  end

  # GET /lives/1
  # GET /lives/1.json
  def show
  end

  # GET /lives/new
  def new
    @life = Live.new
  end

  # GET /lives/1/edit
  def edit
  end

  # POST /lives
  # POST /lives.json
  def create
    @life = Live.new(life_params)

    respond_to do |format|
      if @life.save
        format.html { redirect_to @life, notice: 'Live was successfully created.' }
        format.json { render :show, status: :created, location: @life }
      else
        format.html { render :new }
        format.json { render json: @life.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lives/1
  # PATCH/PUT /lives/1.json
  def update
    respond_to do |format|
      if @life.update(life_params)
        format.html { redirect_to stories_path, notice: 'Live was successfully updated.' }
        format.json { render :show, status: :ok, location: @life }
      else
        format.html { render :edit }
        format.json { render json: @life.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lives/1
  # DELETE /lives/1.json
  def destroy
    @life.destroy
    respond_to do |format|
      format.html { redirect_to lives_url, notice: 'Live was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_life
      @life = Live.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def life_params
      params.require(:live).permit(:title, :source, :url, :thumbnail)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all.order("publish_date DESC")
    @live = Live.first
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :url, :image_url, :tag, :source, :publish_date, :tag_color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lives_helper.rb
module LivesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/cards/_form.html.erb
<div class="jumbotron">
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :photo %><br>
    <%= f.text_field :photo, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :publish_date %><br>
    <%= f.date_select :publish_date%>
  </div>
  <div class="form-group">
    <%= f.label :card_type %><br>
    <%= f.text_field :card_type, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :tag %><br>
    <%= f.text_field :tag, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :card_url %><br>
    <%= f.text_field :card_url, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :source %><br>
    <%= f.text_field :source, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :source_name %><br>
    <%= f.text_field :source_name, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :sponsor %><br>
    <%= f.text_field :sponsor, :class => "form-control"  %>
  </div>
  
  <div>
    <%= f.submit "Save", :class => "btn btn-success" %>
  </div>

<% end %>
</div>

app/views/cards/edit.html.erb
<div class="container">
	<h1>Editing Card</h1>
	<%= render 'form' %>
	<%= link_to 'Show', @card %> |
	<%= link_to 'Back', cards_path %>
</div>

app/views/cards/index.html.erb
<div class="index">
<p id="notice"><%= notice %></p>

<h1>Listing Cards</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Photo</th>
      <th>Date</th>
      <th>Type</th>
      <th>Tag</th>
      <th>Url</th>
      <th>Source</th>
      <th>Source Name</th>
      
      <th>Sponsor</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.title %></td>
        <td><%= card.subtitle %></td>
        <td><%= card.photo %></td>
        <td><%= card.publish_date %></td>
        <td><%= card.card_type %></td>
        <td><%= card.tag %></td>
        <td><%= card.card_url %></td>
        <td><%= card.source %></td>
        <td><%= card.source_name %></td>
        <td><%= card.sponsor %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/cards/new.html.erb
<div class="container">
	<h1>New Card</h1>
	<%= render 'form' %>
	<%= link_to 'Back', cards_path %>
</div>

app/views/cards/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @card.title %></h3>
    </div>
    <div class="panel-body">

      <p>
        <strong>Title:</strong>
        <%= @card.title %>
      </p>

      <p>
        <strong>Subtitle:</strong>
        <%= @card.subtitle %>
      </p>

      <p>
        <strong>Photo:</strong></br>
        <img src="<%= @card.photo %>"></br>
        <%= @card.photo %>
      </p>

      <p>
        <strong>Publish date:</strong>
        <%= @card.publish_date %>
      </p>

      <p>
        <strong>Type:</strong>
        <%= @card.card_type %>
      </p>

      <p>
        <strong>Tag:</strong>
        <%= @card.tag %>
      </p>

      <p>
        <strong>Url:</strong>
        <%= @card.card_url %>
      </p>

      <p>
        <strong>Source:</strong>
        <%= @card.source %>
      </p>
      <p>
        <strong>Source Name:</strong>
        <%= @card.source_name %>
      </p>
      <p>
        <strong>Sponsor:</strong>
        <%= @card.sponsor %>
      </p>
    </div>
  </div>

  <%= link_to 'Edit', edit_card_path(@card) %> |
  <%= link_to 'Back', cards_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Octo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
	<div class="col-md-2">
		<ul class="nav nav-pills nav-stacked">
			<li class="<%= 'active' if params[:controller] == 'cards' %>"><a href="/cards">Cards</a></li>
			<li class="<%= 'active' if params[:controller] == 'stories' %>"><a href="/stories">LiveHub</a></li>
		</ul>
	</div>
	<div class="col-md-10">
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/lives/_form.html.erb
<div class="jumbotron">
  <%= form_for(@life) do |f| %>
    <% if @life.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@life.errors.count, "error") %> prohibited this life from being saved:</h2>

        <ul>
        <% @life.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :source %><br>
      <%= f.text_field :source, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :url %><br>
      <%= f.text_field :url, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :thumbnail %><br>
      <%= f.text_field :thumbnail, :class => "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/lives/edit.html.erb
<div class="container">
<h1>Editing Live</h1>

<%= render 'form' %>
</div>

<%= link_to 'Show', @life %> |
<%= link_to 'Back', stories_path %>

app/views/lives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lives</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Source</th>
      <th>Url</th>

      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lives.each do |life| %>
      <tr>
        <td><%= life.title %></td>
        <td><%= life.source %></td>
        <td><%= life.url %></td>
        <td><%= life.thumbnail %></td>
        <td><%= link_to 'Show', life %></td>
        <td><%= link_to 'Edit', edit_life_path(life) %></td>
        <td><%= link_to 'Destroy', life, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Live', new_life_path %>

app/views/lives/new.html.erb
<div class="container">
<h1>New Life</h1>

<%= render 'form' %>

<%= link_to 'Back', lives_path %>
</div>

app/views/lives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @life.title %>
</p>

<p>
  <strong>Source:</strong>
  <%= @life.source %>
</p>

<p>
  <strong>Url:</strong>
  <%= @life.url %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @life.thumbnail %>
</p>
<%= link_to 'Back', stories_path %>

app/views/stories/_form.html.erb
<div class="jumbotron">
  <%= form_for(@story) do |f| %>
    <% if @story.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

        <ul>
        <% @story.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :url %><br>
      <%= f.text_field :url, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :image_url %><br>
      <%= f.text_field :image_url, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :tag %><br>
      <%= f.text_field :tag, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :source %><br>
      <%= f.text_field :source, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :publish_date %><br>
      <%= f.datetime_select :publish_date, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :tag_color %><br>
      <%= f.text_field :tag_color, :class => "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit "Save", :class => "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Live</h1>
<% if Live.all.count > 0 %>
  <% live = Live.first %>

    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= live.title %></h3>
        <p><%= live.source %></p>
        <p><%= live.url %></p>
        <p><%= live.thumbnail %></p>
        <%= link_to "Edit", controller: "lives", action: "edit", id: live %>   
      </div>
    </div>
<% else %>
  <p> Não há nenhum evento live no momento <p>
  <%= link_to 'New Live', new_life_path, class: "btn btn-primary btn-lg" %>
<% end %>

<h1>Live Hub</h1>

<% @stories.each do |story| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-2">
          <img src="<%= story.image_url %>" class="story_image">
        </div>
        <div class="col-md-8">
          <p class="tag" style="color:<%= story.tag_color %>"><%= story.tag %></p>
          <p class="title"><%= story.title %></p>
          <p>Por <span class="source"><%= story.source %></span></p>
        </div>
        <div class="col-md-2">
          <div class="list-group">
            <%= link_to 'Show', story, :class => "list-group-item" %>
            <%= link_to 'Edit', edit_story_path(story), :class => "list-group-item" %>
            <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }, :class => "list-group-item" %>
          </div>
        </div>     
      </div>
    </div>
  </div>
<% end %>

<br>

<%= link_to 'New Story', new_story_path, class: "btn btn-primary btn-lg" %>

app/views/stories/new.html.erb
<div class="container">
	<h1>New Story</h1>

	<%= render 'form' %>

	<%= link_to 'Back', stories_path %>
</div>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @story.url %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @story.image_url %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @story.tag %>
</p>

<p>
  <strong>Source:</strong>
  <%= @story.source %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @story.publish_date %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>